package com.maskan.csv.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "MessageRelay", targetNamespace = "http://webservice.smsrelay.armaghan.net/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MessageRelay {


    /**
     * @param content
     * @param username
     * @param mClass
     * @param udh
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryUDHOneToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageBinaryUDHOneToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryUDHOneToMany")
    @ResponseWrapper(localName = "sendMessageBinaryUDHOneToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryUDHOneToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryUDHOneToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryUDHOneToManyResponse")
    public ReferenceResult sendMessageBinaryUDHOneToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    String originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    String content,
            @WebParam(name = "udh", targetNamespace = "")
                    String udh,
            @WebParam(name = "mClass", targetNamespace = "")
                    String mClass);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param sourcePort
     * @param destinationPort
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessagePortManyToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessagePortManyToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessagePortManyToMany")
    @ResponseWrapper(localName = "sendMessagePortManyToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessagePortManyToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessagePortManyToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessagePortManyToManyResponse")
    public ReferenceResult sendMessagePortManyToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    List<String> originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    List<String> content,
            @WebParam(name = "destinationPort", targetNamespace = "")
                    List<String> destinationPort,
            @WebParam(name = "sourcePort", targetNamespace = "")
                    List<String> sourcePort,
            @WebParam(name = "mClass", targetNamespace = "")
                    List<String> mClass);

    /**
     * @param id
     * @param username
     * @param password
     * @return returns com.art.remote_db.client.interactive.MessageStateResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/getMessageStateRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessageState", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.GetMessageState")
    @ResponseWrapper(localName = "getMessageStateResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.GetMessageStateResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/getMessageStateRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/getMessageStateResponse")
    public MessageStateResult getMessageState(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "id", targetNamespace = "")
                    List<Long> id);

    /**
     * @param username
     * @param password
     * @return returns com.art.remote_db.client.interactive.UserResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/getUserInfoRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.GetUserInfoResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/getUserInfoRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/getUserInfoResponse")
    public UserResult getUserInfo(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * @param content
     * @param username
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageManyToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageManyToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageManyToMany")
    @ResponseWrapper(localName = "sendMessageManyToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageManyToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageManyToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageManyToManyResponse")
    public ReferenceResult sendMessageManyToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    List<String> originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    List<String> content);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param sourcePort
     * @param destinationPort
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessagePortOneToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessagePortOneToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessagePortOneToMany")
    @ResponseWrapper(localName = "sendMessagePortOneToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessagePortOneToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessagePortOneToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessagePortOneToManyResponse")
    public ReferenceResult sendMessagePortOneToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    String originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    String content,
            @WebParam(name = "destinationPort", targetNamespace = "")
                    String destinationPort,
            @WebParam(name = "sourcePort", targetNamespace = "")
                    String sourcePort,
            @WebParam(name = "mClass", targetNamespace = "")
                    String mClass);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param udh
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageUDHManyToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageUDHManyToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageUDHManyToMany")
    @ResponseWrapper(localName = "sendMessageUDHManyToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageUDHManyToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageUDHManyToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageUDHManyToManyResponse")
    public ReferenceResult sendMessageUDHManyToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    List<String> originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    List<String> content,
            @WebParam(name = "udh", targetNamespace = "")
                    List<String> udh,
            @WebParam(name = "mClass", targetNamespace = "")
                    List<String> mClass);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param udh
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageUDHOneToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageUDHOneToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageUDHOneToMany")
    @ResponseWrapper(localName = "sendMessageUDHOneToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageUDHOneToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageUDHOneToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageUDHOneToManyResponse")
    public ReferenceResult sendMessageUDHOneToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    String originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    String content,
            @WebParam(name = "udh", targetNamespace = "")
                    String udh,
            @WebParam(name = "mClass", targetNamespace = "")
                    String mClass);

    /**
     * @param content
     * @param username
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageOneToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageOneToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageOneToMany")
    @ResponseWrapper(localName = "sendMessageOneToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageOneToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageOneToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageOneToManyResponse")
    public ReferenceResult sendMessageOneToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    String originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    String content);

    /**
     * @param username
     * @param password
     * @return returns com.art.remote_db.client.interactive.CountResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/getReceivedMessageCountRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReceivedMessageCount", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.GetReceivedMessageCount")
    @ResponseWrapper(localName = "getReceivedMessageCountResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.GetReceivedMessageCountResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/getReceivedMessageCountRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/getReceivedMessageCountResponse")
    public CountResult getReceivedMessageCount(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param sourcePort
     * @param destinationPort
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryPortOneToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageBinaryPortOneToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryPortOneToMany")
    @ResponseWrapper(localName = "sendMessageBinaryPortOneToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryPortOneToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryPortOneToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryPortOneToManyResponse")
    public ReferenceResult sendMessageBinaryPortOneToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    String originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    String content,
            @WebParam(name = "destinationPort", targetNamespace = "")
                    String destinationPort,
            @WebParam(name = "sourcePort", targetNamespace = "")
                    String sourcePort,
            @WebParam(name = "mClass", targetNamespace = "")
                    String mClass);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param udh
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryUDHManyToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageBinaryUDHManyToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryUDHManyToMany")
    @ResponseWrapper(localName = "sendMessageBinaryUDHManyToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryUDHManyToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryUDHManyToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryUDHManyToManyResponse")
    public ReferenceResult sendMessageBinaryUDHManyToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    List<String> originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    List<String> content,
            @WebParam(name = "udh", targetNamespace = "")
                    List<String> udh,
            @WebParam(name = "mClass", targetNamespace = "")
                    List<String> mClass);

    /**
     * @param username
     * @param password
     * @return returns com.art.remote_db.client.interactive.MessageResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/pullReceivedMessagesRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pullReceivedMessages", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.PullReceivedMessages")
    @ResponseWrapper(localName = "pullReceivedMessagesResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.PullReceivedMessagesResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/pullReceivedMessagesRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/pullReceivedMessagesResponse")
    public MessageResult pullReceivedMessages(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * @param content
     * @param username
     * @param mClass
     * @param sourcePort
     * @param destinationPort
     * @param originator
     * @param password
     * @param destination
     * @return returns com.art.remote_db.client.interactive.ReferenceResult
     */
    @WebMethod(action = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryPortManyToManyRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageBinaryPortManyToMany", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryPortManyToMany")
    @ResponseWrapper(localName = "sendMessageBinaryPortManyToManyResponse", targetNamespace = "http://webservice.smsrelay.armaghan.net/", className = "com.art.remote_db.client.interactive.SendMessageBinaryPortManyToManyResponse")
    @Action(input = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryPortManyToManyRequest", output = "http://webservice.smsrelay.armaghan.net/MessageRelay/sendMessageBinaryPortManyToManyResponse")
    public ReferenceResult sendMessageBinaryPortManyToMany(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "originator", targetNamespace = "")
                    List<String> originator,
            @WebParam(name = "destination", targetNamespace = "")
                    List<String> destination,
            @WebParam(name = "content", targetNamespace = "")
                    List<String> content,
            @WebParam(name = "destinationPort", targetNamespace = "")
                    List<String> destinationPort,
            @WebParam(name = "sourcePort", targetNamespace = "")
                    List<String> sourcePort,
            @WebParam(name = "mClass", targetNamespace = "")
                    List<String> mClass);

}
