package com.maskan.csv.ws;


import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "MessageRelayService", targetNamespace = "http://webservice.smsrelay.armaghan.net/")
public class MessageRelayService
        extends Service {

    private static String LOAD_BALANCER_IP = "192.168.111.52";
    private static int LOAD_BALANCER_PORT = 8080;

    private final static URL MESSAGERELAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGERELAYSERVICE_EXCEPTION;
    private final static QName MESSAGERELAYSERVICE_QNAME = new QName("http://webservice.smsrelay.armaghan.net/", "MessageRelayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://" + LOAD_BALANCER_IP + ":" + LOAD_BALANCER_PORT + "/core/MessageRelayService?wsdl");
            System.out.println(url);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGERELAYSERVICE_WSDL_LOCATION = url;
        MESSAGERELAYSERVICE_EXCEPTION = e;
    }

    public MessageRelayService() {
        super(__getWsdlLocation(), MESSAGERELAYSERVICE_QNAME);
    }

    public MessageRelayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGERELAYSERVICE_QNAME, features);
    }

    public MessageRelayService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGERELAYSERVICE_QNAME);
    }

    public MessageRelayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGERELAYSERVICE_QNAME, features);
    }

    public MessageRelayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageRelayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGERELAYSERVICE_EXCEPTION != null) {
            throw MESSAGERELAYSERVICE_EXCEPTION;
        }
        return MESSAGERELAYSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns MessageRelay
     */
    @WebEndpoint(name = "MessageRelayPort")
    public MessageRelay getMessageRelayPort() {
        return super.getPort(new QName("http://webservice.smsrelay.armaghan.net/", "MessageRelayPort"), MessageRelay.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MessageRelay
     */
    @WebEndpoint(name = "MessageRelayPort")
    public MessageRelay getMessageRelayPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.smsrelay.armaghan.net/", "MessageRelayPort"), MessageRelay.class, features);
    }

}
